# Generated by Django 4.1.1 on 2022-09-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_title', models.CharField(max_length=50, verbose_name='Обмен')),
                ('swap_lot_1', models.CharField(max_length=50, verbose_name='Лот_1')),
                ('swap_lot_2', models.CharField(max_length=50, verbose_name='Лот_2')),
                ('swap_date', models.DateTimeField(verbose_name='Дата обмена')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_title', models.CharField(max_length=50, verbose_name='Обмен')),
                ('lot_text', models.CharField(max_length=200, verbose_name='Лот_1')),
                ('swap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Swaps.swap')),
            ],
        ),
    ]
