# Generated by Django 4.1.1 on 2022-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Swaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swap',
            options={'verbose_name': 'Свап', 'verbose_name_plural': 'Свапы'},
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
