# Generated by Django 4.1.1 on 2022-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lots', '0003_remove_lot_swap'),
        ('Swaps', '0002_alter_swap_options_delete_lot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swap',
            old_name='swap_lot_2',
            new_name='id_lot_2',
        ),
        migrations.RemoveField(
            model_name='swap',
            name='swap_lot_1',
        ),
        migrations.AddField(
            model_name='swap',
            name='id_lot_1',
            field=models.ManyToManyField(to='Lots.lot'),
        ),
    ]
