# Generated by Django 4.1.1 on 2022-09-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_title', models.CharField(max_length=50, verbose_name='Название')),
                ('lot_text', models.CharField(max_length=200, verbose_name='Описание')),
                ('lot_date', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
            },
        ),
    ]
