# Generated by Django 4.1.1 on 2022-09-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Swaps', '0002_alter_swap_options_delete_lot'),
        ('Lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='swap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Swaps.swap'),
        ),
    ]
