# Generated by Django 4.1.1 on 2022-09-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lots', '0002_lot_swap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='swap',
        ),
    ]
